project:
  type: book
  output-dir: docs

book:
  title: "Comp112 Journal"
  author: "Enrico Verità"
  date: "9/16/2024"
  chapters:
    - index.qmd
    - activities/Multivariate-viz-exercises.qmd
    - activities/EffectiveVizActivities.qmd
    - activities/Spacial_Viz.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

