project:
  type: book
  output-dir: docs

book:
  title: "Comp112 Journal"
  author: "Enrico Verità"
  date: "9/16/2024"
  chapters:
    - index.qmd
    - Multivariate-viz-exercises.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

